# Generated by Django 4.2.16 on 2024-10-03 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliorat', '0012_alter_bookauthor_options_alter_bookprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookwishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'To read'), (1, 'Read - Good'), (2, 'Read - Not so good')], default=0)),
                ('booktitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='bibliorat.bookprofile')),
                ('listowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
