# Generated by Django 4.2.16 on 2024-10-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookwishlist',
            name='personalnotes',
            field=models.TextField(default='Personal notes go here'),
        ),
    ]
