# Generated by Django 4.2.16 on 2024-10-04 04:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwish', '0003_rename_bookwishlist_bookwishitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookwishitem',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
