# Generated by Django 4.2.16 on 2024-09-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliorat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorname', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bookprofile',
            name='bookgenre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='bookprofile',
            name='originallanguage',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='bookprofile',
            name='publicationyear',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
