# Generated by Django 4.2.16 on 2024-09-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliorat', '0002_bookauthor_alter_bookprofile_bookgenre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookprofile',
            name='status',
            field=models.IntegerField(),
        ),
    ]
