# Generated by Django 4.2.16 on 2024-09-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliorat', '0003_alter_bookprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookprofile',
            name='publicationyear',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookprofile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
