# Generated by Django 4.2.16 on 2024-09-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliorat', '0004_alter_bookprofile_publicationyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookprofile',
            name='bookhook',
            field=models.TextField(blank=True),
        ),
    ]
