# Generated by Django 4.2.16 on 2024-09-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliorat', '0005_bookprofile_bookhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookauthor',
            name='authorbio',
            field=models.TextField(blank=True),
        ),
    ]
