# Generated by Django 4.2.16 on 2024-09-30 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliorat', '0006_bookauthor_authorbio'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookprofile',
            name='authorname',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='bibliorat.bookauthor'),
        ),
    ]
