# Generated by Django 4.2.16 on 2024-10-03 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliorat', '0011_remove_bookprofile_profilecontent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookauthor',
            options={'ordering': ['authorname']},
        ),
        migrations.AlterModelOptions(
            name='bookprofile',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ['-created_on']},
        ),
    ]
