# Generated by Django 4.2.16 on 2024-10-04 04:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliorat', '0012_alter_bookauthor_options_alter_bookprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookauthor',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='bookprofile',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
