# Generated by Django 4.2.16 on 2024-10-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliorat', '0013_bookauthor_featured_image_bookprofile_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookprofile',
            name='bookgenre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bookprofile',
            name='originallanguage',
            field=models.CharField(max_length=30),
        ),
    ]
